[package]
name = "peppi-slp"
version = "0.1.0"
authors = ["melkor <hohav@fastmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
hdf5 = "0.7"
jmespatch = { version = "0.3", features = ["specialized"] }
mimalloc = { version = "0.1", default-features = false }
ndarray = "0.13"
num-traits = "0.2"
peppi = { git = "https://github.com/hohav/peppi.git", branch = "const-generics", features = ["hdf5"] }
pretty_env_logger = "0.4"
serde_json = "1.0"
tempfile = "3.1"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
codegen-units = 1
panic = "abort"
incremental = false
rpath = false

[[bin]]
name = "slp"
path = "src/main.rs"
