[package]
name = "peppi-slp"
version = "0.1.0"
authors = ["melkor <hohav@fastmail.com>"]
edition = "2018"

[dependencies]
arrow = "4.4"
clap = "2.33"
parquet = { version = "4.4", default-features = false, features = ["arrow", "base64"] }
parquet-format = "4.0"
peppi = "1.0.0-alpha.2"
pretty_env_logger = "0.4"
serde_json = "1.0"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
codegen-units = 1
incremental = false
rpath = false

[[bin]]
name = "slp"
path = "src/main.rs"
